spring.application.name=kidzbrain

# Configuracion de la DB
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/kidzbrain_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=n0m3l0

# Configuracion de JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Configuracion del TransactionManager
spring.transaction.default-timeout=30
spring.transaction.rollback-on-commit-failure=true

# Tamaño máximo permitido para un solo archivo
spring.servlet.multipart.max-file-size=20MB

# Tamaño máximo de toda la petición
spring.servlet.multipart.max-request-size=25MB

# Configuración para emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${KIDZBRAIN_EMAIL}
spring.mail.password=${KIDZBRAIN_EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
